"""fisrt baru ...

Revision ID: 91386b2bd00b
Revises: ec4bf3f11e38
Create Date: 2025-05-22 11:50:49.643231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91386b2bd00b'
down_revision = 'ec4bf3f11e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('nama', mysql.TEXT(), nullable=True),
    sa.Column('harga', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('stock', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('category', mysql.TEXT(), nullable=True),
    sa.Column('image', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('deskripsi', mysql.TEXT(), nullable=True),
    sa.Column('create_at', mysql.TEXT(), nullable=True),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
